---
title: "Assignment 3, Task 4"
author: "Evie Vermeer"
date: "10/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(here)
library(tidyverse)
library(ggplot2)
library(janitor)
library(kableExtra)
library(lubridate) 
library(plotly)

```

```{r}
urchins <- read_csv(here("data","urchins.csv")) %>% clean_names()
  
```
```{r}
mean_size_purple_urchins <- urchins %>% 
  filter(common_name=="Purple Urchin") %>% 
  group_by(treatment) %>% 
  summarize(mean_size=mean(size))
```


```{r}
naples_purple_urchins_2010 <- urchins %>% 
  mutate(date_new = ymd(date)) %>% 
  mutate(year = year(date_new)) %>% 
  filter(year == "2010",common_name == "Purple Urchin", site == "NAPL") 
  

```

```{r}
ggplot(data=naples_purple_urchins_2010, aes(x=size,fill=treatment))+
      geom_histogram(bins=8, alpha=0.4, position ="identity")+
  facet_wrap(~treatment)
# Debating whether to use facet_wrap to split treatments into separate histograms or overlay them for more easy comparison

      
```

```{r}
ggplot(data=naples_purple_urchins_2010, aes(sample=size))+
      geom_qq()

# This needs work 
```

```{r}
naples_purple_urchins_2010_stats <- naples_purple_urchins_2010 %>% 
  group_by(treatment) %>% 
  summarize(mean_size=mean(size, na.rm= TRUE),
            sd_size=sd(size, na.rm= TRUE),
            sample_size=n())

naples_purple_urchins_2010_stats %>% 
  kable(col.names = c("Treatment",
                      "Mean (mm)",
                      "Standard Deviation(mm)",
                      "Sample size (n)"),
                    caption = "Descriptive Statistics for Purple Urchins on Naples Reef - 2010") %>% 
  kable_styling(full_width=FALSE)
            
```



